esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: ${name_add_mac_suffix}

esp32:
  board: ${board}
  framework:
    type: ${framework_type}

# https://esphome.io/components/wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_ap_name
    password: !secret wifi_ap_password

captive_portal:

# https://esphome.io/components/api
api:
  encryption:
    key: !secret homeassistant_api_key

# https://esphome.io/components/logger
logger:

http_request:
  verify_ssl: false

# https://esphome.io/components/ota
ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_password
  - platform: http_request
    id: ota_http_request

# mqtt:
#   broker: !secret mqtt_address
#   port: !secret mqtt_port
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   topic_prefix: null
#   discovery: False
#   discover_ip: False