packages:
  device_base: !include .defaults.yaml

# For M5Stack AtomS3R datasheet check product page at https://docs.m5stack.com/en/core/AtomS3R
substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: m5stack-atom-s3r            # hostname & entity_id
  name_add_mac_suffix: "false"             # append MAC address to device_name
  friendly_name: M5Stack AtomS3R           # Displayed in HA frontend
  board: esp32-s3-devkitc-1                # ESP32 board
  framework_type: arduino                  # ESP32 framework

# logger:
#   level: VERY_VERBOSE
#   logs:
#     wifi: NONE
#     api.service: INFO
#     api.socket: INFO
#     scheduler: INFO
#     esp32.preferences: INFO
#     mdns: INFO
#     wifi_esp32: INFO
#     app: INFO
#     ili9xxx: INFO
#     ic2: INFO

esphome:
  project:
    name: esphome.m5stack-atom-s3r
    version: dev
  libraries:
    - M5Unified=https://github.com/m5stack/M5Unified#0.2.4
  platformio_options:
      build_flags: -DI2C_BUFFER_LENGTH=8193

external_components:
  - source: components


### Specific instructions for the M5Stack AtomS3R board

# sensor:
#   # - platform: m5stack_button_compound_sensor
#   #   m5stack_button_sensor_number:
#   #     name: Button State Number
#   #   m5stack_button_sensor_text:
#   #     name: Button State Text
#   - platform: bmi270_bmm150
#     update_interval: 5s
#     acceleration_x:
#       name: "IMU Accel X"
#     acceleration_y:
#       name: "IMU Accel Y"
#     acceleration_z:
#       name: "IMU Accel z"
#     gyroscope_x:
#       name: "IMU Gyro X"
#     gyroscope_y:
#       name: "IMU Gyro Y"
#     gyroscope_z:
#       name: "IMU Gyro z"
#     field_strength_x:
#       name: "IMU Mag X"
#     field_strength_y:
#       name: "IMU Mag Y"
#     field_strength_z:
#       name: "IMU Mag z"
#     temperature:
#       name: "IMU Temperature"

text_sensor:
#   - platform: m5stack_button_text_sensor
#     name: Button State Text
  # - platform: mqtt_subscribe
  #   name: "Teams Presence"
  #   id: teams_status
  #   topic: sensor/teams_status
  # - platform: mqtt_subscribe
  #   name: "Teams Call Status"
  #   id: teams_call
  #   topic: homeassistant/sensor/teams_call
  - platform: homeassistant
    name: "Teams Status"
    entity_id: sensor.teams_status
    id: teams_status

# sensor:
#   - platform: m5stack_imu_sensor
#     update_interval: 5s
#     acceleration_x:
#       name: "IMU Accel X"
#     acceleration_y:
#       name: "IMU Accel Y"
#     acceleration_z:
#       name: "IMU Accel z"
#     gyroscope_x:
#       name: "IMU Gyro X"
#     gyroscope_y:
#       name: "IMU Gyro Y"
#     gyroscope_z:
#       name: "IMU Gyro z"
#     field_strength_x:
#       name: "IMU Mag X"
#     field_strength_y:
#       name: "IMU Mag Y"
#     field_strength_z:
#       name: "IMU Mag z"
#     temperature:
#       name: "IMU Temperature"

#G41 = Button
binary_sensor:
  - platform: gpio
    name: Button
    id: main_button
    pin:
      number: 41
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms
    on_press:
      then:
        - logger.log: binary_sensor button pressed
    on_double_click:
      then:
        - logger.log: binary_sensor button double clicked
    on_multi_click:
      - timing:
        - ON for at least 1s
        then:
          - logger.log: binary_sensor button hold
  - platform: homeassistant
    name: "Teams In Call"
    entity_id: binary_sensor.teams_in_call
    id: teams_in_call
  - platform: homeassistant
    name: "Webcam Active"
    entity_id: binary_sensor.3zrttq3_3zrttq3_webcamactive
    id: webcam_active
  # - platform: homeassistant
  #   name: "PC Muted"
  #   entity_id: binary_sensor.pc_muted
  #   id: pc_muted

# I2C Addresses:
#   0x30 = LP5562 / Display Backlight
#   0x68 = BMI270 / IMU
i2c:
  sda: 45
  scl: 0
  scan: false # Disable I2C scan to speed up boot time
  frequency: 400kHz
  # timeout: 200us # doesn't work with idf

light:
  - platform: monochromatic
    output: displaybacklightoutput
    initial_state:
      state: true
    restore_mode: ALWAYS_ON
    name: M5Stack Display Backlight
    id: displaybacklight
    icon: mdi:television-ambient-light

output:
  - platform: m5stack_display_backlight_output
    id: displaybacklightoutput

spi:
  clk_pin: 15
  mosi_pin: 21

display:
  - platform: ili9xxx
    model: st7789v
    id: display_tft
    dimensions:
      height: 128
      width: 128
      offset_height: 1
      offset_width: 2
    cs_pin: 14
    dc_pin: 42
    reset_pin: 48
    invert_colors: true   # black bg, white text
    rotation: 0           # 180 = cable is bottom, 90 = cable is left
    lambda: |-
      const char* state = id(teams_status).state.c_str();
      bool is_in_call = id(teams_in_call).state;
      bool is_webcam_active = id(webcam_active).state;
      bool is_button_click = id(main_button).state;
      if (strcmp(state, "Available") == 0 || strcmp(state, "Away") == 0 || strcmp(state, "Unknown") == 0 || strcmp(state, "Offline") == 0 || (strcmp(state, "Busy") == 0 && !is_in_call)) {
        it.filled_rectangle(0, 0, it.get_width(), 40, id(green));
        if (strcmp(state, "Busy") == 0 && !is_in_call) {
          it.image(128, 0, id(calendar), ImageAlign::TOP_RIGHT, id(red), id(green));
          it.print(it.get_width()/2-5, 0, id(font_default), TextAlign::TOP_CENTER, "Free");
        } else {
          it.print(it.get_width()/2, 0, id(font_default), TextAlign::TOP_CENTER, "Free");
        }
        if (!is_webcam_active) {
          it.image(it.get_width()/2, it.get_height()/2-7, id(camera_off), ImageAlign::CENTER_HORIZONTAL);
        } else {
          it.image(it.get_width()/2, it.get_height()/2-7, id(camera), ImageAlign::CENTER_HORIZONTAL, id(red));
        }
      } else if (strcmp(state, "Busy") == 0 && is_in_call) {
        it.filled_rectangle(0, 0, it.get_width(), 40, id(red));
        it.print(it.get_width()/2, 0, id(font_default), TextAlign::TOP_CENTER, "Meeting");
        if (!is_webcam_active) {
          it.image(it.get_width()/2, it.get_height()/2-7, id(camera_off), ImageAlign::CENTER_HORIZONTAL);
        } else {
          it.image(it.get_width()/2, it.get_height()/2-7, id(camera), ImageAlign::CENTER_HORIZONTAL, id(red));
        }
      } else if (strcmp(state, "Do Not Disturb") == 0) {
        it.filled_rectangle(0, 0, it.get_width(), 40, id(pink));
        it.print(it.get_width()/2, 0, id(font_default), TextAlign::TOP_CENTER, "Meeting");
        if (!is_webcam_active) {
          it.image(it.get_width()/2, it.get_height()/2-7, id(camera_off), ImageAlign::CENTER_HORIZONTAL);
        } else {
          it.image(it.get_width()/2, it.get_height()/2-7, id(camera), ImageAlign::CENTER_HORIZONTAL, id(red));
        }
      } else {
        it.printf(0, 0, id(font_mini), id(grey), "state: %s", state);
        it.printf(0, 8, id(font_mini), id(grey), "in_call: %s", is_in_call ? "true" : "false");
        it.printf(0, 16, id(font_mini), id(grey), "cam_active: %s", is_webcam_active ? "true" : "false");
        it.printf(0, 24, id(font_mini), id(grey), "button_click: %s", is_button_click ? "true" : "false");
        it.printf(it.get_width()/2, it.get_height()/2-10, id(font_small), TextAlign::TOP_CENTER, "Loading...");
      }
      it.strftime(128, 128, id(font_small), id(white), TextAlign::BOTTOM_RIGHT, "%H:%M", id(ha_time).now());

font:
  - file: "gfonts://Roboto"
    id: font_default
    size: 32
  - file: "gfonts://Roboto"
    id: font_small
    size: 16
  - file: "gfonts://Roboto"
    id: font_mini
    size: 10

image:
  - file: mdi:camera
    type: grayscale
    transparency: alpha_channel
    id: camera
    resize: 40x40
  - file: mdi:camera-off
    type: grayscale
    transparency: alpha_channel
    id: camera_off
    resize: 40x40
  - file: mdi:calendar
    type: grayscale
    transparency: alpha_channel
    id: calendar
    resize: 20x20

color:
  - id: red
    red: 100%
    green: 20%
    blue: 25%
  - id: green
    red: 0%
    green: 80%
    blue: 5%
  - id: white
    red: 100%
    green: 100%
    blue: 100%
  - id: grey
    red: 40%
    green: 40%
    blue: 40%
  - id: pink
    red: 70%
    green: 0%
    blue: 70%

time:
  platform: homeassistant
  id: ha_time