packages:
  m5stack-atom-s3r: !include m5stack-atom-s3r.yaml

esphome:
  project:
    name: esphome.m5stack-atom-s3r
    version: dev
  libraries:
    - M5Unified=https://github.com/m5stack/M5Unified#0.2.4

improv_serial:

http_request:
  verify_ssl: false

ota:
  - platform: http_request
    id: ota_http_request

# update:
#   - platform: http_request
#     id: update_http_request
#     name: Firmware
#     source: https://firmware.esphome.io/bluetooth-proxy/m5stack-atom-s3/manifest.json

# dashboard_import:
#   package_import_url: github://esphome/bluetooth-proxies/m5stack/m5stack-atom-s3.yaml@main